# Generated by Django 4.0.4 on 2022-04-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('date', models.DateTimeField(auto_now=True, primary_key=True, serialize=False, verbose_name='Date Collected')),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('humidity', models.IntegerField(verbose_name='Humidity')),
                ('pressure', models.IntegerField(verbose_name='Pressure')),
            ],
        ),
    ]
