# Generated by Django 4.0.4 on 2022-04-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='date',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Date Collected'),
        ),
    ]
