# Generated by Django 4.0.4 on 2022-05-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_datapoint_sensor_alter_sensor_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='air_direction',
            field=models.CharField(choices=[('N', 'North'), ('NE', 'North East'), ('E', 'East'), ('SE', 'South East'), ('S', 'South'), ('SW', 'South West'), ('W', 'West'), ('NW', 'North West')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='air_speed',
            field=models.FloatField(default=1.0, verbose_name='Air Speed'),
        ),
    ]
