# Generated by Django 4.0.4 on 2022-08-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_datapoint_air_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='humidity',
            field=models.FloatField(verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='pressure',
            field=models.FloatField(verbose_name='Pressure'),
        ),
    ]
